on: [push]

jobs:
  phpcs:
    name: Run PHPCS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Specify your PHP version here
        extensions: mbstring

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --no-interaction

    - name: Install PHP CodeSniffer
      run: composer global require "squizlabs/php_codesniffer=*"

    - name: Run PHPCS
      run: ~/.composer/vendor/bin/phpcs --standard=Drupal src/ # Update the path and standard as needed

    - name: Upload PHPCS report
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: phpcs-report
        path: phpcs.xml
