name: PHP Composer

on: [push]
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock ${{ github.workspace }}
      run: composer validate
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Install PHP CodeSniffer
      run: composer global require "squizlabs/php_codesniffer=*"

    - name: Run PHPCS
      run: ~/.composer/vendor/bin/phpcs --standard=PSR12 app/src/ # Update the path and standard as needed

    - name: Upload PHPCS report
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: phpcs-report
        path: phpcs.xml

    # - name: Run test suite
    #   run: composer run-script test
